#!/usr/bin/env python3
"""Build the two Nitori X single-header profiles from one ordered source set."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src"
MANIFEST = SOURCE / "manifest.txt"
TARGETS = {
    "checked": ROOT / "Nitori.h",
    "unsafe": ROOT / "Nitori_unsafe.h",
}


def modules() -> list[Path]:
    names = [line.strip() for line in MANIFEST.read_text().splitlines()]
    names = [name for name in names if name and not name.startswith("#")]
    paths = [SOURCE / name for name in names]
    missing = [str(path) for path in paths if not path.is_file()]
    if missing:
        raise RuntimeError("missing Nitori X modules: " + ", ".join(missing))
    return paths


def render(profile: str) -> str:
    macro = "NITORI_X_CHECKED" if profile == "checked" else "NITORI_X_UNSAFE"
    out = [
        "#pragma once\n",
        "// Generated by tools/amalgamate.py. Do not edit this file directly.\n",
        f"#define {macro} 1\n",
    ]
    for path in modules():
        text = path.read_text()
        if "#pragma once" in text:
            raise RuntimeError(f"module must not contain #pragma once: {path}")
        out.append(f"\n// ---- {path.name} ----\n")
        out.append(text.rstrip() + "\n")
    return "".join(out)


def digest(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated headers are stale")
    args = parser.parse_args()

    failed = False
    for profile, target in TARGETS.items():
        expected = render(profile)
        if args.check:
            actual = target.read_text() if target.exists() else ""
            if actual != expected:
                print(f"stale: {target}", file=sys.stderr)
                failed = True
            else:
                print(f"ok {profile}: {digest(actual)}")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected)
            print(f"wrote {target}: {digest(expected)}")
    return int(failed)


if __name__ == "__main__":
    raise SystemExit(main())
